//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedLinkApplication.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderEquipment = new HashSet<OrderEquipment>();
        }
    
        public int Id { get; set; }
        public int OrderStatusId { get; set; }
        public int ManagerId { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public int ServiceId { get; set; }
        public int ClientId { get; set; }
        public int AddressId { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public System.DateTime OrderDateTime { get; set; }
        public Nullable<System.DateTime> CompleteDatetime { get; set; }
        public string Description { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Client Client { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderEquipment> OrderEquipment { get; set; }
    }
}
